lib/sna_web/router.ex
defmodule SnaWeb.Router do
  use SnaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :check_auth
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :check_auth
    plug PhoenixSwagger.Plug.Validate
  end

  pipeline :authenticated do
    plug :ensure_auth
  end

  scope "/", SnaWeb do
    pipe_through :browser

    get "/", PageController, :index

    get  "/auth/", AuthController, :index
    post "/auth/email", AuthController, :email
    get  "/auth/email", AuthController, :email
    get  "/auth/logout", AuthController, :logout
  end

  scope "/providers" do
    pipe_through [:browser, :authenticated]

    get "/:provider_name/oauth", SnaWeb.ProviderOAuthController, :request
    get "/:provider_name/oauth/callback", SnaWeb.ProviderOAuthController, :callback
  end

  scope "/entries" do
    pipe_through [:browser, :authenticated]

    live "/new",                 SnaWeb.EntriesLive.Form, session: [:path_params, :auth]
    get  "/new/.",               SnaWeb.EntriesController, :new # Helpers only
    get  "/",                    SnaWeb.EntriesController, :index
    get  "/:id",                 SnaWeb.EntriesController, :show
    live "/:id/edit",            SnaWeb.EntriesLive.Form, session: [:path_params, :auth]
    get  "/:id/edit/.",          SnaWeb.EntriesController, :edit # Helpers only
    post "/:id/delete",          SnaWeb.EntriesController, :destroy
    get  "/:id/campaign",        SnaWeb.EntriesCampaignController, :show
    post "/:id/campaign",        SnaWeb.EntriesCampaignController, :update
    post "/:id/campaign/delete", SnaWeb.EntriesCampaignController, :destroy
    get  "/:id/campaign/new",    SnaWeb.EntriesCampaignController, :new
    get  "/:id/campaign/edit",   SnaWeb.EntriesCampaignController, :edit
  end

  scope "/campaigns" do
    pipe_through [:browser, :authenticated]
    get  "/",                      SnaWeb.CampaignsController, :index
  end

  scope "/scheduled_entries" do
    pipe_through [:browser, :authenticated]
    post "/", SnaWeb.ScheduledEntriesController, :create
  end

  scope "/api/v0", as: "api_v0" do
    pipe_through [:api, :authenticated]

    post   "/entries",     SnaWeb.Api.EntriesController, :create
    patch  "/entries/:id", SnaWeb.Api.EntriesController, :update
  end

  scope "/api/v0/swagger" do
    forward "/", PhoenixSwagger.Plug.SwaggerUI, otp_app: :sna, swagger_file: "swagger.json"
  end

  def swagger_info do
    %{
      info: %{
        version: "0.1",
        title: "SNA"
      }
    }
  end
end

lib/sna/repo/campaign.ex
defmodule Sna.Repo.Campaign do

  @moduledoc """

  Sna.Repo.Provider is the Ecto Abstration of the `campaigns` table present
  in database.

  """

  use Ecto.Schema
  import Ecto.Changeset

  @type t :: %__MODULE__{
    id:    nil | integer,
    name:  String.t,
    user:  Sna.Repo.User.t,
    entry: Sna.Repo.Entry.t,
  }

  @type changeset :: Ectp.Changeset.t(t)

  schema "campaigns" do
    field :name, :string

    belongs_to :user,              Sna.Repo.User
    belongs_to :entry,             Sna.Repo.Entry
    has_many   :scheduled_entries, Sna.Repo.ScheduledEntry
  end

  @spec changeset(t | changeset | Ecto.Schema.t, map) :: changeset
  def changeset(model, params) do
    model
      |> cast(params, [:name])
      |> cast_assoc(:scheduled_entries, with: &Sna.Repo.ScheduledEntry.changeset/1)
      |> validate_required([:name])
      |> validate_length(:name, min: 1)
      |> unique_constraint(:entry_id)
  end

  @spec changeset(t | changeset | Ecto.Schema.t | map) :: changeset
  def changeset(%__MODULE__{} = model), do: changeset(model, %{})
  def changeset(%{} = params), do: changeset(%__MODULE__{}, params)

  @spec get_by_entry_id(integer) :: __MODULE__.t | nil
  def get_by_entry_id(entry_id) do
    import Ecto.Query
    Sna.Repo.one(
      from c in __MODULE__,
      join: e in assoc(c, :entry),
      preload: [entry: e],
      where: c.entry_id == ^entry_id)
  end

  @spec all_from_user_id(integer) :: [__MODULE__.t]
  def all_from_user_id(uid) do
    import Ecto.Query
    Sna.Repo.all(
      from c in __MODULE__,
      join: e in assoc(c, :entry),
      join: r in assoc(e, :entry_user_relations),
      preload: [entry: e],
      where: r.user_id == ^uid
    )
  end

  @spec exists_by_entry_id?(integer) :: boolean
  def exists_by_entry_id?(entry_id) do
    import Ecto.Query
    Sna.Repo.exists?(
      from c in __MODULE__,
      where: c.entry_id == ^entry_id)
  end

  #spec insert_or_update(changeset) :: (({:ok, __MODULE__.t}) | ({:error, changeset}))
  def insert_or_update(changeset) do
    Sna.Repo.insert_or_update(changeset)
  end
end

lib/sna_web/controllers/campaigns_controller.ex
defmodule SnaWeb.CampaignsController do
  use SnaWeb, :controller

  @spec index(Plug.Conn.t, Plug.Conn.params) :: Plug.Conn.t
  def index(conn, _params) do
    conn
      |> render("index.html",
        campaigns: Sna.Repo.Campaign.all_from_user_id(current_user(conn).id))
  end
end

lib/sna_web/views/campaigns_view.ex
defmodule SnaWeb.CampaignsView do
  use SnaWeb, :view
end

lib/sna_web/templates/campaigns/_actions.html.eex
<div>
  <a href="<%= Routes.entries_campaign_path(@conn, :show, @entry.id) %>">view</a>
  <a href="<%= Routes.entries_campaign_path(@conn, :edit, @entry.id) %>">edit</a>
  <%= form_for @conn, Routes.entries_campaign_path(@conn, :destroy, @entry.id), [method: :post, class: :link], fn _f -> %>
    <%= submit "delete", class: :link %>
  <% end %>
</div>

lib/sna_web/templates/campaigns/_form.html.leex
<%= f = form_for @changeset, Routes.entries_campaign_path(@socket, :update, @entry.id), [phx_change: :validate, phx_submit: :save, crsf_token: @crsf_token] %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <p>
  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>
  </p>

  <div>
    <%= submit "Save", phx_disable_with: "Saving..." %>
  </div>
</form>

lib/sna_web/templates/campaigns/_preview.html.eex
<h1><a href="<%= Routes.entries_campaign_path(@conn, :show, @campaign.entry_id) %>">Campaign: <%= @campaign.name %></a></h1>
<%= render(@view_module, "_actions.html", assigns) %>
<%= render(SnaWeb.EntriesView, "show.html", conn: @conn, entry: @entry, hide_campaign: true) %>

lib/sna_web/templates/campaigns/edit.html.eex
<h1>Edit campaign</h1>
<%= render(@view_module, "_actions.html", conn: @conn, entry: @session.entry) %>
<%= live_render(@conn, SnaWeb.EntriesCampaignLive.Form, session: @session) %>

lib/sna_web/templates/campaigns/index.html.eex
<%= if length(@campaigns) > 0 do %>

<div class="campaigns list">
<%= for campaign <- @campaigns do %>
  <article class="campaign item">
    <%= render(@view_module, "_preview.html", conn: @conn, campaign: campaign, entry: campaign.entry) %>
  </article>
<% end %>
</div>

<% end %>

lib/sna_web/templates/campaigns/new.html.eex
<h1>New campaign for entry</h1>
<%= render(@view_module, "_actions.html", conn: @conn, entry: @session.entry) %>
<%= live_render(@conn, SnaWeb.EntriesCampaignLive.Form, session: @session) %>

lib/sna_web/templates/campaigns/show.html.eex
<h1>Campaign: <%= @campaign.name %></h1>
<%= render(@view_module, "_actions.html", assigns) %>

<%= if length(@providers) == 0 do %>
<p><em>To publish this campaign on a social network, you must first associate with one.</em></p>
<% else %>
Add social network:
<ul class="inline actions">
  <%= for provider <- @providers do %>
  <li>
    <%= form_for @conn, Routes.scheduled_entries_path(@conn, :create), [method: :post, class: :link], fn _f -> %>
      <input type="hidden" name="scheduled_entry[provider_id]" value="<%= provider.id %>" />
      <input type="hidden" name="scheduled_entry[campaign_id]" value="<%= @campaign.id %>" />
      <%= submit provider.name, class: :link %>
    <% end %>
  </li>
  <% end %>
</ul>
<% end %>

<div class="entries list">
  <article class="entry item">
    <%= render(SnaWeb.EntriesView, "show.html", conn: @conn, entry: @entry, hide_campaign: true) %>
  </article>
  <%= for scheduled_entry <- @campaign.scheduled_entries do %>
  <article class="scheduled_entry item">
    Scheduled entry for <%= scheduled_entry.provider.name %>
  </article>
  <% end %>
</div>