lib/sna_web/router.ex
defmodule SnaWeb.Router do
  use SnaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :check_auth
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :check_auth
    plug PhoenixSwagger.Plug.Validate
  end

  pipeline :authenticated do
    plug :ensure_auth
  end

  scope "/", SnaWeb do
    pipe_through :browser

    get "/", PageController, :index

    get  "/auth/", AuthController, :index
    post "/auth/email", AuthController, :email
    get  "/auth/email", AuthController, :email
    get  "/auth/logout", AuthController, :logout
  end

  scope "/providers" do
    pipe_through [:browser, :authenticated]

    get "/:provider_name/oauth", SnaWeb.ProviderOAuthController, :request
    get "/:provider_name/oauth/callback", SnaWeb.ProviderOAuthController, :callback
  end

  scope "/entries" do
    pipe_through [:browser, :authenticated]

    live "/new",                 SnaWeb.EntriesLive.Form, session: [:path_params, :auth]
    get  "/new/.",               SnaWeb.EntriesController, :new # Helpers only
    get  "/",                    SnaWeb.EntriesController, :index
    get  "/:id",                 SnaWeb.EntriesController, :show
    live "/:id/edit",            SnaWeb.EntriesLive.Form, session: [:path_params, :auth]
    get  "/:id/edit/.",          SnaWeb.EntriesController, :edit # Helpers only
    post "/:id/delete",          SnaWeb.EntriesController, :destroy
    get  "/:id/campaign",        SnaWeb.EntriesCampaignController, :show
    post "/:id/campaign",        SnaWeb.EntriesCampaignController, :update
    post "/:id/campaign/delete", SnaWeb.EntriesCampaignController, :destroy
    get  "/:id/campaign/new",    SnaWeb.EntriesCampaignController, :new
    get  "/:id/campaign/edit",   SnaWeb.EntriesCampaignController, :edit
  end

  scope "/campaigns" do
    pipe_through [:browser, :authenticated]
    get  "/",                      SnaWeb.CampaignsController, :index
  end

  scope "/scheduled_entries" do
    pipe_through [:browser, :authenticated]
    post "/", SnaWeb.ScheduledEntriesController, :create
  end

  scope "/api/v0", as: "api_v0" do
    pipe_through [:api, :authenticated]

    post   "/entries",     SnaWeb.Api.EntriesController, :create
    patch  "/entries/:id", SnaWeb.Api.EntriesController, :update
  end

  scope "/api/v0/swagger" do
    forward "/", PhoenixSwagger.Plug.SwaggerUI, otp_app: :sna, swagger_file: "swagger.json"
  end

  def swagger_info do
    %{
      info: %{
        version: "0.1",
        title: "SNA"
      }
    }
  end
end

lib/sna_web/views/layout_view.ex
defmodule SnaWeb.LayoutView do
  use SnaWeb, :view

  def meta(conn, assigns) do
    case [view_module(conn), view_template(conn)] do
    [nil, _] -> nil
    [view, nil] ->
      render_existing(view, "meta/meta.html", assigns)
    [view, template] ->
      render_existing(view, "meta/meta." <> template, assigns) ||
      render_existing(view, "meta/meta.html", assigns)
    end ||
      render_existing(SnaWeb.LayoutView, "_meta.html", assigns) ||
      ""
  end

  def page_title(conn, assigns) do
    case view_module(conn) do
    nil -> nil
    view ->
      try do
        case action_name(conn) do
          nil    -> apply(view, :page_title, [assigns])
          action -> apply(view, :page_title, [action, assigns])
        end
      rescue
        UndefinedFunctionError -> nil
      end
    end
  end
end

lib/sna_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= meta(@conn, assigns) %>
    <title><%=
      [page_title(@conn, assigns), "Social Network Automation"]
        |> Enum.reject(&is_nil/1)
        |> Enum.join(" · ")
    %></title>
  </head>
  <body>
    <header>
      <nav role="logo">
        <a href="<%= Routes.page_path(@conn, :index) %>">SNA</a>
      </nav>
      <nav role="navigation">
        <ul>
          <li><a href="<%= Routes.entries_path(@conn, :index) %>">All Entries</a></li>
          <li><a href="<%= Routes.campaigns_path(@conn, :index) %>">All Campaigns</a></li>
          <li><a href="<%= Routes.entries_path(@conn, :new) %>">New Entry</a></li>
        </ul>
      </nav>
      <nav role="login">
        <ul>
          <%=
          case current_user(@conn) do
            %{email: email} ->
            raw "<li>Authenticated as #{email} <a href=\"/auth/logout\">log-out</a></li>"
            _ ->
              raw "<li><a href=\"/auth\">Authenticate</a></li>"
          end
          %>
        </ul>
      </nav>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>